global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - scheme: http
      timeout: 10s
      api_version: v1
      static_configs:
        - targets: [ "localhost:9091" ]
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: 1C_Metrics
#    honor_timestamps: true
#    scrape_interval: 15s
#    scrape_timeout: 10s
    metrics_path: /metrics
#    scheme: http
    static_configs:
      - targets:
          - 192.168.57.145:9091